@startuml Action

class Action <<(O,lime)>>
Action : name_preferred : str - o - nr
Action : name_variant : str - r
Action : references : ExternalReference - r 
Action : bibliographical_references : Citation - r

class Heading <<(A,green)>>

class Thing <<(O,lime)>>

class Iconography <<(A,green)>>

class Criterion <<(A,green)>>

class Option  <<(A,green)>>

class Cycle <<(G,blue)>>

class EdgeHeadingAction  <<(E,yellow)>>
EdgeHeadingAction : numberA : int - nr
EdgeHeadingAction : numberB : int - nri
EdgeHeadingAction : previewA : str - nr
EdgeHeadingAction : previewB : str - nr

class EdgeThingAction <<(E,yellow)>>
EdgeThingAction : numberA : int - nr
EdgeThingAction : numberB : int - nr
EdgeThingAction : previewA : str - nr
EdgeThingAction : previewB : str - nr

class EdgeActionAction <<(E,yellow)>>
EdgeActionAction : numberA : int - nr
EdgeActionAction : numberB : int - nr
EdgeActionAction : previewA : str - nr
EdgeActionAction : previewB : str - nr
EdgeActionAction : copy_variants : bool - o - nr

class EdgeActionIconography <<(E,yellow)>>
EdgeActionIconography : numberA : int - nr
EdgeActionIconography : numberB : int - nr
EdgeActionIconography : previewA : str - nr
EdgeActionIconography : previewB : str - nr
EdgeActionIconography : copy_variants : bool - o - nr

class EdgeActionCriterion <<(E,yellow)>>
EdgeActionCriterion : number : int - nr - o 

class EdgeActionOption <<(E,yellow)>>
EdgeActionOption : numberA : int - nr
EdgeActionOption : numberB : int - nr
EdgeActionOption : previewA : str - nr
EdgeActionOption : previewB : str - nr

class EdgeActionCycle <<(E,yellow)>>
EdgeActionCycle : numberA : int - nr
EdgeActionCycle : numberB : int - nr
EdgeActionCycle : previewA : str - nr
EdgeActionCycle : previewB : str - nr


Heading "0..n" -- "1" EdgeHeadingAction: related action >
EdgeHeadingAction "1" -- "0..n" Action: related concept <

Thing "0..n" -- "1" EdgeThingAction: used for >
EdgeThingAction "1" -- "0..n" Action: tool <

Action "0..n" -- "1" EdgeActionAction: child action >
EdgeActionAction "1" -- "0..n" Action: parent action <

Action "0..n" -- "1" EdgeActionIconography : example of >
EdgeActionIconography "1" -- "0..n" Iconography : example for <

Action "0..n" -- "1" EdgeActionOption : additional action in >
EdgeActionOption "1" -- "0..n" Option : additionally shown Action <

Action "0..n" -- "1" EdgeActionCriterion : > can be connected to \n these Criteria 
EdgeActionCriterion "1" -- "1" Criterion : \n Criterion linked to <

Action "0..n" -- "1" EdgeActionCycle : related image cycles >
EdgeActionCycle "1" -- "0..n" Cycle : theme of cycle <

@enduml