@startuml 
class Book 
Book : references : external_reference - r
Book : title : str - o - nr
Book : parent title : str - nr
Book : volume number : str - nr
Book : date : date - nr
Book : all catalogued? : boolean - o - nr
Book : all catalogued? - comments : str - nr

class Person 

class Place

class Manuscript

class EdgeToArtwork
EdgeToArtwork : current? : boolean - o - nr
EdgeToArtwork : page number for display : str - nr
EdgeToArtwork : sequence number : perhaps tuple \n                  of two integers - nr

class Artwork

Book "0..n" --- "0..n" Place : published in > \n place of publication of <

Book "0..n" --- "0..n" Person : author was > \n author of <

Book "0..n" --- "0..1" Manuscript : used in > \n printed model was <

Book "0..n" --- "1" EdgeToArtwork : contains > 

EdgeToArtwork "1" --- "0..1" Artwork : in <

@enduml 
