@startuml Copy
class Copy <<(I,red)>>
 Copy : bibliographical_references : Citation - r

class Image <<(I,red)>>

class Photo <<(I,red)>>

class Organisation <<(O,lime)>>

class EdgeImageCopy <<(E,yellow)>>
EdgeImageCopy : preferred : bool - o - nr

class EdgeCopyPhoto <<(E,yellow)>>
EdgeCopyPhoto : preferred : bool - o - nr

class EdgeCopyCollection <<(E,yellow)>>
EdgeCopyCollection : current? : boolean - o - nr
EdgeCopyCollection : catalogue : str - nr
EdgeCopyCollection : inventory_no_preferred : str - nr
EdgeCopyCollection : inventory_no_other : str - r
EdgeCopyCollection : date : Date - nr


Image "0..n" -- "1" EdgeImageCopy : represented in >
EdgeImageCopy "1" -- "1" Copy : represents <

Copy "0..n"  -- "1" EdgeCopyPhoto : photographed in >
EdgeCopyPhoto "1" -- "1" Photo : photograph of <

Copy "0..n" -- "1" EdgeCopyCollection : in >
EdgeCopyCollection "1" -- "0..n" Organisation : has <


@enduml