@startuml Cycle

class Cycle <<(G,blue)>>
Cycle : medium : str - o - r
Cycle : name_preferred: str -  nr 
Cycle : name_variant: str - r
Cycle : bibliographical_references : Citation - r
class MakingProcess

class Person <<(O,lime)>>

class Family <<(O,lime)>>

class Office <<(O,lime)>>

class Personification <<(O,lime)>>

class Organisation <<(O,lime)>>

class OrganisationTheme <<(O,lime)>>

class Place <<(O,lime)>>

class PlaceTheme <<(O,lime)>>

class NaturalObject <<(O,lime)>>

class Thing <<(O,lime)>>

class Action <<(O,lime)>>

class MakingProcess <<(I,red)>>

class Manuscript <<(O,green)>>

class Book <<(O,green)>>

class Image <<(I,red)>>

class EdgePersonCycleTheme <<(E,yellow)>>
EdgePersonCycleTheme : numberA : int - nr
EdgePersonCycleTheme : numberB : int - nr
EdgePersonCycleTheme : previewA : str - nr
EdgePersonCycleTheme : previewB : str - nr

class EdgeFamilyCycleTheme <<(E,yellow)>>
EdgeFamilyCycleTheme : numberA : int - nr
EdgeFamilyCycleTheme : numberB : int - nr
EdgeFamilyCycleTheme : previewA : str - nr
EdgeFamilyCycleTheme : previewB : str - nr

class EdgeOfficeCycleTheme <<(E,yellow)>>
EdgeOfficeCycleTheme : numberA : int - nr
EdgeOfficeCycleTheme : numberB : int - nr
EdgeOfficeCycleTheme : previewA : str - nr
EdgeOfficeCycleTheme : previewB : str - nr

class EdgePersonificationCycle  <<(E,yellow)>>
EdgePersonificationCycle : numberA : int - nr
EdgePersonificationCycle : numberB : int - nr
EdgePersonificationCycle : previewA : str - nr
EdgePersonificationCycle : previewB : str - nr

class EdgeOrganisationCycleTheme  <<(E,yellow)>>
EdgeOrganisationCycleTheme : numberA : int - nr
EdgeOrganisationCycleTheme : numberB : int - nr
EdgeOrganisationCycleTheme : previewA : str - nr
EdgeOrganisationCycleTheme : previewB : str - nr

class EdgePlaceCycleTheme  <<(E,yellow)>>
EdgePlaceCycleTheme : numberA : int - nr
EdgePlaceCycleTheme : numberB : int - nr
EdgePlaceCycleTheme : previewA : str - nr
EdgePlaceCycleTheme : previewB : str - nr

class EdgeNaturalObjectCycleTheme  <<(E,yellow)>>
EdgeNaturalObjectCycleTheme : numberA : int - nr
EdgeNaturalObjectCycleTheme : numberB : int - nri
EdgeNaturalObjectCycleTheme : previewA : str - nr
EdgeNaturalObjectCycleTheme : previewB : str - nr

class EdgeThingCycle  <<(E,yellow)>>
EdgeThingCycle : numberA : int - nr
EdgeThingCycle : numberB : int - nr
EdgeThingCycle : previewA : str - nr
EdgeThingCycle : previewB : str - nr

class EdgeActionCycle  <<(E,yellow)>>
EdgeActionCycle : numberA : int - nr
EdgeActionCycle : numberB : int - nr
EdgeActionCycle : previewA : str - nr
EdgeActionCycle : previewB : str - nr



class EdgeCycleMakingProcess  <<(E,yellow)>>
EdgeCycleMakingProcess : number - int - o - nr
EdgeCycleMakingProcess : partial - bool - o - nr

class EdgeManuscriptCycle  <<(E,yellow)>>
EdgeManuscriptCycle : current : boolean - o - nr
EdgeManuscriptCycle : partial : boolean - o - nr
EdgeManuscriptCycle : page number for display : str - nr
EdgeManuscriptCycle : sequence number : perhaps tuple \n              of two integers - nr

class EdgeBookCycle  <<(E,yellow)>>
EdgeBookCycle : page number for display : str - nr
EdgeBookCycle : sequence number : perhaps tuple \n                  of two integers - nr

class EdgeCycleCollection  <<(E,yellow)>>
EdgeCycleCollection : current? : boolean - o - nr
EdgeCycleCollection : partial : boolean - o - nr
EdgeCycleCollection : catalogue : str - nr
EdgeCycleCollection : inventory_no_preferred : str - nr
EdgeCycleCollection : inventory_no_other : str - r
EdgeCycleCollection : date : Date - nr

class EdgePlaceCycle  <<(E,yellow)>>
EdgePlaceCycle : current : bool -  o - nr
EdgePlaceCycle : partial : bool - o - nr
EdgePlaceCycle : date : Date - nr

class EdgeImageCycle <<(E,yellow)>>
EdgeImageCycle : sequence_number : int - o - nr
EdgeImageCycle : number : str




Person "0..n" -- "1" EdgePersonCycleTheme : related image cycles >
EdgePersonCycleTheme "1" -- "0..n" Cycle : theme of cycle <

Family "0..n" -- "1" EdgeFamilyCycleTheme : related image cycles >
EdgeFamilyCycleTheme "1" -- "0..n" Cycle : theme of cycle <

Personification "0..n" -- "1" EdgePersonificationCycle : related image cycles >
EdgePersonificationCycle "1" -- "0..n" Cycle : theme of cycle <

Office "0..n" -- "1" EdgeOfficeCycleTheme : related image cycles >
EdgeOfficeCycleTheme "1" -- "0..n" Cycle : theme of cycle <

OrganisationTheme "0..n" -- "1" EdgeOrganisationCycleTheme : related image cycles >
EdgeOrganisationCycleTheme "1" -- "0..n" Cycle : theme of cycle <

PlaceTheme "0..n" -- "1" EdgePlaceCycleTheme : related image cycles >
EdgePlaceCycleTheme "1" -- "0..n" Cycle : theme of cycle <

NaturalObject "0..n" -- "1" EdgeNaturalObjectCycleTheme : related image cycles >
EdgeNaturalObjectCycleTheme "1" -- "0..n" Cycle : theme of cycle <

Thing "0..n" -- "1" EdgeThingCycle : related image cycles >
EdgeThingCycle "1" -- "0..n" Cycle : theme of cycle <

Action "0..n" -- "1" EdgeActionCycle : related image cycles >
EdgeActionCycle "1" -- "0..n" Cycle : theme of cycle <

Cycle "0..n" -- "1" EdgeCycleMakingProcess 
EdgeCycleMakingProcess "1" -- "0..n" MakingProcess

Cycle "0..n" -- "1" EdgePlaceCycle : < in
EdgePlaceCycle  "1" -- "0..n" Place :  location of  >

Cycle "0..n" -- "1" EdgeCycleCollection : in >
EdgeCycleCollection "1" -- "0..n" Organisation : has  <

Cycle "0..n" -- "1" EdgeManuscriptCycle : in > 
EdgeManuscriptCycle "1" -- "0..n" Manuscript : contains <

Cycle "0..1" -- "1" EdgeBookCycle : in > 
EdgeBookCycle "1" -- "0..n" Book : contains <

Cycle "0..n" -- "1" EdgeImageCycle : > contains
EdgeImageCycle "1" -- "0..n" Image : belongs to <

@enduml