@startuml ExternalReference

class ExternalReference

ExternalReference : number : int - nr
ExternalReference : id : str - o - nr 
ExternalReference : name : str - o - nr 
ExternalReference : uri : str - o - nr 

@enduml