@startuml Family

class Family <<(O,lime)>>
Family : references : ExternalReference - r
Family : name_preferred : str - o - nr
Family : name_variant : str - r
Family : date : Date - nr
Family : bibliographical_references : Citation - r

class Person <<(O,lime)>>

class Heading <<(A,green)>>

class Place <<(O,lime)>>

class Office <<(O,lime)>>

class Text <<(O,lime)>>

class Iconography <<(A,green)>>

class Criterion <<(A,green)>>

class Option <<(A,green)>>

class Cycle <<(G,blue)>>

class EdgeFamilyPlace <<(E,yellow)>>
EdgeFamilyPlace : date : Date - nr

class EdgeFamilyOffice <<(E,yellow)>>
EdgeFamilyOffice : date : Date - nr

class EdgeFamilyIconography <<(E,yellow)>>
EdgeFamilyIconography : numberA : int - nr
EdgeFamilyIconography : numberB : int - nr
EdgeFamilyIconography : previewA : str - nr
EdgeFamilyIconography : previewB : str - nr
EdgeFamilyIconography : copy_variants - bool - nr

class EdgeFamilyCriterion <<(E,yellow)>>
EdgeFamilyCriterion : number : int - nr - o 

class EdgeFamilyOption <<(E,yellow)>>
EdgeFamilyOption : numberA : int - nr
EdgeFamilyOption : numberB : int - nr
EdgeFamilyOption : previewA : str - nr
EdgeFamilyOption : previewB : str - nr
EdgeFamilyOption : copy_variants : bool - o - nr

class EdgeFamilyCycle <<(E,yellow)>>
EdgeFamilyCycle : numberA : int - nr
EdgeFamilyCycle : numberB : int - nr
EdgeFamilyCycle : previewA : str - nr
EdgeFamilyCycle : previewB : str - nr

Person "0..n" --- "0..n" Family : > member of \n has member <

Text "0..n" --- "0..n" Family : > describes \n appears in by <

Heading "0..n" --- "0..n" Family :  > has example \n is example for <

Place "0..n" -- "1" EdgeFamilyPlace : lived here >
EdgeFamilyPlace "1" -- "0..n" Family : lived in <

Office "0..n" -- "1" EdgeFamilyOffice : office was held frequently by >
EdgeFamilyOffice "1" -- "0..n" Family : had frequently office <

Family "0..n" -- "1" EdgeFamilyIconography : coat-of-arms >
EdgeFamilyIconography "1" -- "0..n" Iconography : coat-of-arms of <

Family "0..n" -- "1" EdgeFamilyCriterion : > can be connected to \n these Criteria 
EdgeFamilyCriterion "1" -- "1" Criterion : \n Criterion linked to <

Family "0..n" -- "1" EdgeFamilyOption : additionally portrayed in >
EdgeFamilyOption "1" -- "0..n" Option : additional portrayed person <

Family "0..n" -- "1" EdgeFamilyCycle : related image cycles >
EdgeFamilyCycle "1" -- "0..n" Cycle : theme of cycle <




@enduml



