@startuml Iconography
class Iconography <<(A,green)>>
Iconography : type : str - o - nr
Iconography : references : ExternalReference - r
Iconography : name_preferred : str - o - nr
Iconography : name_variant : str - r
Iconography : bibliographical_references : Citation - r

class Person <<(O,lime)>>

class Family <<(O,lime)>>

class Personification <<(O,lime)>>

class Organisation <<(O,lime)>>

class Place <<(O,lime)>>

class NaturalObject <<(O,lime)>>

class Thing <<(O,lime)>>

class Text <<(O,lime)>>

class Action <<(O,lime)>>

class Artwork <<(I,red)>>

class Criterion  <<(A,green)>>

class Image <<(I,red)>>

class EdgePersonIconography <<(E,yellow)>>
EdgePersonIconography : numberA : int - nr
EdgePersonIconography : numberB : int - nri
EdgePersonIconography : previewA : str - nr
EdgePersonIconography : previewB : str - nr
EdgePersonIconography : copy_variants : bool - o - nr

class EdgeFamilyIconography <<(E,yellow)>>
EdgeFamilyIconography : numberA : int - nr
EdgeFamilyIconography : numberB : int - nr
EdgeFamilyIconography : previewA : str - nr
EdgeFamilyIconography : previewB : str - nr
EdgeFamilyIconography : copy_variants - bool - nr

class EdgePersonificationIconography <<(E,yellow)>>
EdgePersonificationIconography : numberA : int - nr
EdgePersonificationIconography : numberB : int - nri
EdgePersonificationIconography : previewA : str - nr
EdgePersonificationIconography : previewB : str - nr
EdgePersonificationIconography : copy_variants : bool - o - nr

class EdgeOrganisationIconography <<(E,yellow)>>
EdgeOrganisationIconography : numberA : int - nr
EdgeOrganisationIconography : numberB : int - nr
EdgeOrganisationIconography : previewA : str - nr
EdgeOrganisationIconography : previewB : str - nr
EdgeOrganisationIconography : copy_variants : bool - o - nr

class EdgePlaceIconography <<(E,yellow)>>
EdgePlaceIconography : numberA : int - nr
EdgePlaceIconography : numberB : int - nr
EdgePlaceIconography : previewA : str - nr
EdgePlaceIconography : previewB : str - nr
EdgePlaceIconography : copy_variants : bool - o - nr

class EdgeNaturalObjectIconography <<(E,yellow)>>
EdgeNaturalObjectIconography : numberA : int - nr
EdgeNaturalObjectIconography : numberB : int - nri
EdgeNaturalObjectIconography : previewA : str - nr
EdgeNaturalObjectIconography : previewB : str - nr
EdgeNaturalObjectIconography : copy_variants : bool - o - nr

class EdgeThingIconography <<(E,yellow)>>
EdgeThingIconography : numberA : int - nr
EdgeThingIconography : numberB : int - nri
EdgeThingIconography : previewA : str - nr
EdgeThingIconography : previewB : str - nr
EdgeThingIconography : copy_variants : bool - o - nr

class EdgeTextIconography <<(E,yellow)>>
EdgeTextIconography : numberA : int - nr
EdgeTextIconography : numberB : int - nr
EdgeTextIconography : previewA : str - nr
EdgeTextIconography : previewB : str - nr
EdgeTextIconography : copy_variants : bool - o - nr

class EdgeActionIconography <<(E,yellow)>>
EdgeActionIconography : numberA : int - nr
EdgeActionIconography : numberB : int - nri
EdgeActionIconography : previewA : str - nr
EdgeActionIconography : previewB : str - nr
EdgeActionIconography : copy_variants : bool - o - nr

class EdgeArtworkIconography <<(E,yellow)>>
EdgeArtworkIconography : numberA : int - nr
EdgeArtworkIconography : numberB : int - nr
EdgeArtworkIconography : previewA : str - nr
EdgeArtworkIconography : previewB : str - nr
EdgeArtworkIconography : copy_variants : bool - o - nr

class EdgeIconographyCriterion <<(E,yellow)>>
EdgeIconographyCriterion : number : int- o - nr

class EdgeImageIconography <<(E,yellow)>>
EdgeImageIconography : preferred : bool - o - nr
EdgeImageIconography : number : int - o - nr
EdgeImageIconography : qualifier : str - o - nr
EdgeImageIconography : qualifier_comment : str - nr
EdgeImageIconography : options : id  - r



Person "0..n" -- "1" EdgePersonIconography : portrayed in >
EdgePersonIconography "1" -- "0..n" Iconography : portrayed person <

Family "0..n" -- "1" EdgeFamilyIconography : coat-of-arms >
EdgeFamilyIconography "1" -- "0..n" Iconography : coat-of-arms of <

Personification "0.n" -- "1" EdgePersonificationIconography : shown in >
EdgePersonificationIconography "1" -- "0..n" Iconography : shows <

Organisation "0..n" -- "1" EdgeOrganisationIconography : shows members of >
EdgeOrganisationIconography "1" -- "0..n" Iconography : portrayed persons belong to <

Place "0..n" -- "1" EdgePlaceIconography : view >
EdgePlaceIconography "1" -- "0..n" Iconography : view of <

NaturalObject "0..n" -- "1" EdgeNaturalObjectIconography : view >
EdgeNaturalObjectIconography "1" -- "0..n" Iconography : view of <

Thing "0..n" -- "1" EdgeThingIconography : view >
EdgeThingIconography "1" -- "0..n" Iconography : view of <

Text "0..n" -- "1" EdgeTextIconography : source of >
EdgeTextIconography "1" -- "0..n" Iconography : source <

Action "0..n" -- "1" EdgeActionIconography : example of >
EdgeActionIconography "1" -- "0..n" Iconography : example for <

Artwork "0..n" -- "1" EdgeArtworkIconography : image of>
EdgeArtworkIconography "1" -- "0..n" Iconography : image image <

Iconography "0..n" -- "1" EdgeIconographyCriterion : has variants >
EdgeIconographyCriterion "1" -- "1" Criterion : variant of <

Iconography "0..n" -- "1" EdgeImageIconography : shown in >
EdgeImageIconography "1" -- "0..n" Image : showns  <


@enduml