@startuml Iconography
class Iconography
Iconography : type : str - o - nr
Iconography : references : ExternalReference - r
Iconography : name_preferred : str - o - nr
Iconography : name_variant : str - r

class Person 

class Family

class Organisation

class Place

class NaturalObject

class Text

class Action

class Artwork

class Criterion

class Image

class EdgePersonIconography
EdgePersonIconography : numberA : int - nr
EdgePersonIconography : numberB : int - nri
EdgePersonIconography : previewA : str - nr
EdgePersonIconography : previewB : str - nr
EdgePersonIconography : copy_variants : bool - o - nr

class EdgeFamilyIconography
EdgeFamilyIconography : numberA : int - nr
EdgeFamilyIconography : numberB : int - nr
EdgeFamilyIconography : previewA : str - nr
EdgeFamilyIconography : previewB : str - nr
EdgeFamilyIconography : copy_variants - bool - nr

class EdgeOrganisationIconography
EdgeOrganisationIconography : numberA : int - nr
EdgeOrganisationIconography : numberB : int - nr
EdgeOrganisationIconography : previewA : str - nr
EdgeOrganisationIconography : previewB : str - nr
EdgeOrganisationIconography : copy_variants : bool - o - nr

class EdgePlaceIconography
EdgePlaceIconography : numberA : int - nr
EdgePlaceIconography : numberB : int - nr
EdgePlaceIconography : previewA : str - nr
EdgePlaceIconography : previewB : str - nr
EdgePlaceIconography : copy_variants : bool - o - nr

class EdgeNaturalObjectIconography
EdgeNaturalObjectIconography : numberA : int - nr
EdgeNaturalObjectIconography : numberB : int - nri
EdgeNaturalObjectIconography : previewA : str - nr
EdgeNaturalObjectIconography : previewB : str - nr
EdgeNaturalObjectIconography : copy_variants : bool - o - nr

class EdgeTextIconography
EdgeTextIconography : numberA : int - nr
EdgeTextIconography : numberB : int - nr
EdgeTextIconography : previewA : str - nr
EdgeTextIconography : previewB : str - nr
EdgeTextIconography : copy_variants : bool - o - nr

class EdgeActionIconography
EdgeActionIconography : numberA : int - nr
EdgeActionIconography : numberB : int - nri
EdgeActionIconography : previewA : str - nr
EdgeActionIconography : previewB : str - nr
EdgeActionIconography : copy_variants : bool - o - nr

class EdgeArtworkIconography
EdgeArtworkIconography : numberA : int - nr
EdgeArtworkIconography : numberB : int - nr
EdgeArtworkIconography : previewA : str - nr
EdgeArtworkIconography : previewB : str - nr
EdgeArtworkIconography : copy_variants : bool - o - nr

class EdgeIconographyCriterion
EdgeIconographyCriterion : number : int- o - nr

class EdgeImageIconography
EdgeImageIconography : preferred : bool - o - nr
EdgeImageIconography : number : int - o - nr
EdgeImageIconography : qualifier : str - o - nr
EdgeImageIconography : qualifier_comment : str - nr
EdgeImageIconography : qualifier_comments : str - nr
EdgeImageIconography : options : id  - r



Person "0..n" -- "1" EdgePersonIconography : portrayed in >
EdgePersonIconography "1" -- "0..n" Iconography : portrayed person <

Family "0..n" -- "1" EdgeFamilyIconography : coat-of-arms >
EdgeFamilyIconography "1" -- "0..n" Iconography : coat-of-arms of <

Organisation "0..n" -- "1" EdgeOrganisationIconography : shows members of >
EdgeOrganisationIconography "1" -- "0..n" Iconography : portrayed persons belong to <

Place "0..n" -- "1" EdgePlaceIconography : view >
EdgePlaceIconography "1" -- "0..n" Iconography : view of <

NaturalObject "0..n" -- "1" EdgeNaturalObjectIconography : view >
EdgeNaturalObjectIconography "1" -- "0..n" Iconography : view of <

Text "0..n" -- "1" EdgeTextIconography : source of >
EdgeTextIconography "1" -- "0..n" Iconography : source <

Action "0..n" -- "1" EdgeActionIconography : example of >
EdgeActionIconography "1" -- "0..n" Iconography : example for <

Artwork "0..n" -- "1" EdgeArtworkIconography : image of>
EdgeArtworkIconography "1" -- "0..n" Iconography : image image <

Iconography "0..n" -- "1" EdgeIconographyCriterion : has variants >
EdgeIconographyCriterion "1" -- Criterion : variant of <

Iconography "0..n" -- "1" EdgeImageIconography : shown in >
EdgeImageIconography "1" -- "0..n" Image : showns  <


@enduml