@startuml
class MakingProcess <<(I,red)>>
MakingProcess : type - str - o - nr
MakingProcess : qualifier - str - o - nr
MakingProcess : qualifier_comment - str - nr
MakingProcess : partial - bool - o - nr
MakingProcess : partial_detail - str - nr
MakingProcess : date - Date - nr

class Person <<(O,lime)>>

class Organisation <<(O,lime)>>

class Place <<(O,lime)>>

class Artwork <<(I,red)>>

class Cycle <<(G,blue)>>

class Matrix <<(G,blue)>>

class EdgeArtworkMakingProcess <<(E,yellow)>>
EdgeArtworkMakingProcess : number - int - o - nr

class EdgeCycleMakingProcess  <<(E,yellow)>>
EdgeCycleMakingProcess : number - int - o - nr
EdgeCycleMakingProcess : partial - bool - o - nr



class EdgeMatrixMakingProcess <<(E,yellow)>>
EdgeMatrixMakingProcess : number - int - o - nr


Matrix "1..n" -- "1" EdgeMatrixMakingProcess
EdgeMatrixMakingProcess "1" -- "1" MakingProcess

Artwork "1..n" -- "1" EdgeArtworkMakingProcess
EdgeArtworkMakingProcess "1" -- "1" MakingProcess

Cycle "0..n" -- "1" EdgeCycleMakingProcess 
EdgeCycleMakingProcess "1" -- "0..n" MakingProcess


MakingProcess "0..1" -- "0..n" Person : > made by \n  made <

MakingProcess "0..1" -- "0..n" Organisation : > made by \n  made <

MakingProcess "1" -- "0..n" Place  : < made in \n was place of making of >

@enduml

