@startuml Matrix

class Matrix <<(G,blue)>>
Matrix : medium:: str - o - r
Matrix : name_preferred: str -  nr 
Matrix : name_variant: str - r

class Artwork <<(I,red)>>

class MakingProcess <<(I,red)>>

class Text <<(O,lime)>>

class Iconography <<(A,green)>>

class EdgeMatrixMakingProcess <<(E,yellow)>>
EdgeMatrixMakingProcess : number - int - o - nr

class EdgeMatrixIconography <<(E,yellow)>>
EdgeMatrixIconography : preferred : bool - o - nr
EdgeMatrixIconography : number : int - o - nr
EdgeMatrixIconography : qualifier : str - o - nr
EdgeMatrixIconography : qualifier_comment : str - nr
EdgeMatrixIconography : qualifier_comments : str - nr
EdgeMatrixIconography : options : id  - r



Matrix "0..n" -- "1" EdgeMatrixMakingProcess
EdgeMatrixMakingProcess "1" -- "1" MakingProcess

Artwork "0..n" --- "1..n" Matrix : < impression of \n matrix of >

Matrix "0..n" --- "0..n" Text : > can illustrate \n can be illustration of <

Matrix "0..n" -- "1" EdgeMatrixIconography : can show >
EdgeMatrixIconography "1" -- "0..n" Iconography : can be shown in <



@enduml 

