@startuml  NaturalObject
class NaturalObject <<(O,lime)>>
NaturalObject : type : str - o - nr 
NaturalObject : name_preferred : str - o - nr 
NaturalObject : name_translated : str - nr 
NaturalObject : name_variant : str - r 
NaturalObject : references : ExternalReference - r 
NaturalObject : bibliographical_references : Citation - r

class Iconography <<(A,green)>>

class Criterion <<(A,green)>>

class Option <<(A,green)>>

class Cycle <<(G,blue)>>

class HeraldicObject <<(O,lime)>>

class Heading <<(A,green)>>

class EdgeNaturalObjectNaturalObject <<(E,yellow)>>
EdgeNaturalObjectNaturalObject : number : int - o - nr 

class EdgeHeadingNaturalObject  <<(E,yellow)>>
EdgeHeadingNaturalObject : numberA : int - nr
EdgeHeadingNaturalObject : numberB : int - nri
EdgeHeadingNaturalObject : previewA : str - nr
EdgeHeadingNaturalObject : previewB : str - nr



class EdgeNaturalObjectIconography <<(E,yellow)>>
EdgeNaturalObjectIconography : numberA : int - nr
EdgeNaturalObjectIconography : numberB : int - nri
EdgeNaturalObjectIconography : previewA : str - nr
EdgeNaturalObjectIconography : previewB : str - nr
EdgeNaturalObjectIconography : copy_variants : bool - o - nr

class EdgeNaturalObjectCriterion <<(E,yellow)>>
EdgeNaturalObjectCriterion : number : int - o - nr

class EdgeNaturalObjectOption <<(E,yellow)>>
EdgeNaturalObjectOption : numberA : int - nr
EdgeNaturalObjectOption : numberB : int - nri
EdgeNaturalObjectOption : previewA : str - nr
EdgeNaturalObjectOption : previewB : str - nr
EdgeNaturalObjectOption : copy_variants : bool - o - nr

class EdgeNaturalObjectCycleTheme <<(E,yellow)>>
EdgeNaturalObjectCycleTheme : numberA : int - nr
EdgeNaturalObjectCycleTheme : numberB : int - nri
EdgeNaturalObjectCycleTheme : previewA : str - nr
EdgeNaturalObjectCycleTheme : previewB : str - nr


EdgeNaturalObjectNaturalObject "0..n" -- "1" NaturalObject : part of >
EdgeNaturalObjectNaturalObject "1" -- "0..n or 1" NaturalObject: has part >

Heading "0..n" -- "1" EdgeHeadingNaturalObject : has example >
EdgeHeadingNaturalObject "1" -- "0..n" NaturalObject : is example of <

NaturalObject "0..n" -- "1" EdgeNaturalObjectIconography : view >
EdgeNaturalObjectIconography "1" -- "0..n" Iconography : view of <

NaturalObject "0..n" -- "1" EdgeNaturalObjectCriterion : > can be connected to \n these Criteria 
EdgeNaturalObjectCriterion "1" -- "1" Criterion : \n Criterion linked to <

NaturalObject "0..n" -- "1" EdgeNaturalObjectOption : shown as attribute >
EdgeNaturalObjectOption "1" -- "0..n" Option : attribute <

NaturalObject "0..n" -- "1" EdgeNaturalObjectCycleTheme : related image cycles >
EdgeNaturalObjectCycleTheme "1" -- "0..n" Cycle : theme of cycle <

HeraldicObject "0..n" --- "0..n" NaturalObject: > in heraldry \n object form nature <

@enduml