@startuml Person
class Person <<(O,lime)>>
Person : type : str - o - r
Person : references : ExternalReference - r
Person : name_preferred : str - o - nr
Person : name_variant : str - r
Person : sex : str - nr
Person : date : Date - nr
Person : bibliographical_references : Citation - r


class Family <<(O,lime)>>

class Office <<(A,green)>>

class Organisation <<(O,lime)>>

class Place <<(O,lime)>>

class Iconography <<(A,green)>>

class Option <<(A,green)>>
    
class Criterion <<(A,green)>>

class Cycle <<(G,blue)>>

class Text <<(O,lime)>>

class HeraldicObject <<(O,lime)>>

class Book <<(A,green)>>

class Heading <<(A,green)>>

class MakingProcess <<(I,red)>>

class Photo <<(I,red)>>

class Campaign <<(A,green)>>

class EdgePersonPerson <<(E,yellow)>>
EdgePersonPerson : date : Date - nr

class EdgeHeadingPerson  <<(E,yellow)>>
EdgeHeadingPerson : numberA : int - nr
EdgeHeadingPerson : numberB : int - nri
EdgeHeadingPerson : previewA : str - nr
EdgeHeadingPerson : previewB : str - nr

class EdgePersonOffice <<(E,yellow)>>
EdgePersonOffice : date : Date - nr

class EdgePersonOrganisation <<(E,yellow)>>
EdgePersonOrganisation : date : Date - nr

class EdgePersonPlace <<(E,yellow)>>
EdgePersonPlace : date : Date - nr

class EdgePersonIconography <<(E,yellow)>>
EdgePersonIconography : numberA : int - nr
EdgePersonIconography : numberB : int - nr
EdgePersonIconography : previewA : str - nr
EdgePersonIconography : previewB : str - nr

class EdgePersonOption <<(E,yellow)>>
EdgePersonOption : numberA : int - nr
EdgePersonOption : numberB : int - nr
EdgePersonOption : previewA : str - nr
EdgePersonOption : previewB : str - nr
EdgePersonIconography : copy_variants : bool - o - nr

class EdgePersonCriterion <<(E,yellow)>>
EdgePersonCriterion : number : int - nr - o 

class EdgePersonCycle <<(E,yellow)>>
EdgePersonCycle : numberA : int - nr
EdgePersonCycle : numberB : int - nr
EdgePersonCycle : previewA : str - nr
EdgePersonCycle : previewB : str - nr

EdgePersonPerson "1" -- "0..n" Person : father of >
EdgePersonPerson "1" -- "0..n" Person : son of <

Heading "0..n" -- "1" EdgeHeadingPerson : > has example
EdgeHeadingPerson "1" -- "0..n" Person :  is example for <

Family "0..n" --- "0..n" Person : > has member \n member of <

Office "0..n" -- "1" EdgePersonOffice : office held by >
EdgePersonOffice "1" -- "0..n" Person :  has office <

Organisation "0..n" -- "1" EdgePersonOrganisation : has member >
EdgePersonOrganisation "1" -- "0..n" Person : member of <

Place "0..n" -- "1" EdgePersonPlace : born here >
EdgePersonPlace "1" -- "0..n" Person : born in  <

HeraldicObject "0..n" --- "0..n" Person: > person \n in heraldry <

Person "0..n" -- "1" EdgePersonIconography : portrayed in >
EdgePersonIconography "1" -- "0..n" Iconography : portrayed person <

Person "0..n" -- "1" EdgePersonOption : additionally portrayed in >
EdgePersonOption "1" -- "0..n" Option : additional portrayed person <

Person "0..n" -- "1" EdgePersonCriterion : > can be connected to \n these Criteria 
EdgePersonCriterion "1" -- "1" Criterion : \n Criterion linked to <

Person "0..n" -- "1" EdgePersonCycle : related image cycles >
EdgePersonCycle "1" -- "0..n" Cycle : theme of cycle <

Text "0..n" --- "0..n" Person : > Author was \n Author of < 

Person "0..n" --- "0..n" Book : > Author of \n Author was < 

Person "0..n" --- "1" MakingProcess : < made \n was artist of >

Person "0..n" --- "0..n" Photo : < photographed by \n photographed >

Person "0..n" --- "0..n" Campaign : < responsible \n led campaign >

@enduml 
