@startuml Place 

class Place <<(O,lime)>>
Place : type : str - o - nr
Place : references : ExternalReference - r
Place : name_preferred : str - o - nr
Place : name_variant : str - r
Place : coordinates_n : format to be determined - nr
Place : coordinates_s : format to be determined - nr
Place : coordinates_e : format to be determined - nr
Place : coordinates_w : format to be determined - nr
Place : date : Date - nr
Place : bibliographical_references : Citation - r


class Person <<(O,lime)>>

class Family <<(O,lime)>>

class Office <<(A,green)>>

class Organisation <<(O,lime)>>

class Place <<(O,lime)>>

class HeraldicObject <<(0,lime)>>

class Iconography <<(A,green)>>

class Option <<(A,green)>>
    
class Criterion <<(A,green)>>

class Cycle <<(G,blue)>>

class Book <<(A,green)>>

class Heading <<(A,green)>>

class MakingProcess <<(I,red)>>

class Artwork <<(I,red)>>

class EdgeHeadingPlace  <<(E,yellow)>>
EdgeHeadingPlace : numberA : int - nr
EdgeHeadingPlace : numberB : int - nri
EdgeHeadingPlace : previewA : str - nr
EdgeHeadingPlace : previewB : str - nr

class EdgeOfficePlace  <<(E,yellow)>>
EdgeOfficePlace : numberA : int - nr
EdgeOfficePlace : numberB : int - nri
EdgeOfficePlace : previewA : str - nr
EdgeOfficePlace : previewB : str - nr

class EdgePersonPlace <<(E,yellow)>>
EdgePersonPlace : date : Date - nr

class EdgePlaceFamily <<(E,yellow)>>
EdgePlaceFamily : date : Date - nr

class EdgeOrganisationPlace <<(E,yellow)>>
EdgeOrganisationPlace : date : Date - nr

class EdgePlacePlace <<(E,yellow)>>
EdgePlacePlace : date : Date - nr

class EdgePlaceIconography <<(E,yellow)>>
EdgePlaceIconography : numberA : int - nr
EdgePlaceIconography : numberB : int - nr
EdgePlaceIconography : previewA : str - nr
EdgePlaceIconography : previewB : str - nr
EdgePlaceIconography : copy_variants : bool - o - nr

class EdgePlaceCriterion <<(E,yellow)>>
EdgePlaceCriterion : number : int - nr - o 

class EdgePlaceOption <<(E,yellow)>>
EdgePlaceOption : numberA : int - nr
EdgePlaceOption : numberB : int - nr
EdgePlaceOption : previewA : str - nr
EdgePlaceOption : previewB : str - nr
EdgePlaceOption : copy_variants : bool - o - nr

class EdgePlaceCycle <<(E,yellow)>>
EdgePlaceCycle : numberA : int - nr
EdgePlaceCycle : numberB : int - nr
EdgePlaceCycle : previewA : str - nr
EdgePlaceCycle : previewB : str - nr

class EdgePlaceArtwork <<(E,yellow)>>
EdgePlaceArtwork : current : bool : o - nr
EdgePlaceArtwork : date : Date - nr

Person "0..n" -- "1" EdgePersonPlace : born in >
EdgePersonPlace "1" -- "0..n" Place : born here <

Family "0..n" -- "1" EdgePlaceFamily: place of activity >
EdgePlaceFamily "1" -- "0..n" Place :  active here <

Office "0..n" -- "1" EdgeOfficePlace : > office in
EdgeOfficePlace "1" -- "0..n" Place :  offices here <

Organisation "0..n" -- "1" EdgeOrganisationPlace : located in >
EdgeOrganisationPlace "1" -- "0..n" Place : located here <

HeraldicObject "0..n" --- "0..n" Place : > place \n in heraldry <

EdgePlacePlace "1" -- "0..n" Place : has part >
EdgePlacePlace "1" -- "1 or 1..n" Place : part of <

Place "0..n" -- "1" EdgePlaceIconography : view >
EdgePlaceIconography "1" -- "0..n" Iconography : view of <

Place "0..n" -- "1" EdgePlaceCriterion : > can be connected to \n these Criteria 
EdgePlaceCriterion "1" -- "1" Criterion : \n Criterion linked to <

Place "0..n" -- "1" EdgePlaceOption : additionally depicted in >
EdgePlaceOption "1" -- "0..n" Option : additional depicted place <

Place "0..n" -- "1" EdgePlaceCycle : related image cycles >
EdgePlaceCycle "1" -- "0..n" Cycle : theme of cycle <

Book "0..n" --- "0..n" Place : > published in  \n place of publication of <

Heading "0..n" -- "1" EdgeHeadingPlace : > has example
EdgeHeadingPlace "1" -- "0..n" Place :  is example for <

Place "0..n" --- "1" MakingProcess : < made in \n was place of making of >

Place "0..n" -- "1" EdgePlaceArtwork : < in
EdgePlaceArtwork  "1" -- "0..n" Artwork :   location of >

@enduml 
