@startuml Text
class Text <<(O,lime)>>
Text : type : str - o - nr
Text : references : ExternalReference - r
Text : numbering : str - nr
Text : name_preferred : str - nr
Text : name_translated : str - nr
Text : name_variant : str - r
Text : date : Date - nr
Text : bibliography : Bibliography - r
Text : duplicate : bool - o - nr
Text : bibliographical_references : Citation - r

class Person <<(O,lime)>>

class Family <<(O,lime)>>

class Iconography <<(A,green)>>

class Option <<(A,green)>>
    
class Cycle <<(G,blue)>>

class Book <<(A,green)>>

class Manuscript <<(A,green)>>

class Heading <<(A,green)>>

class Artwork <<(I,red)>>

class Matrix <<(G,blue)>>

class Inscription <<(I,red)>>

class Iconography <<(A,green)>>

class Criterion <<(A,green)>>

class Option <<(A,green)>>

class EdgeTextText <<(E,yellow)>>
EdgeTextText : number : int - nr

class EdgeHeadingText  <<(E,yellow)>>
EdgeHeadingText : numberA : int - nr
EdgeHeadingText : numberB : int - nri
EdgeHeadingText : previewA : str - nr
EdgeHeadingText : previewB : str - nr

class EdgeTextIconography <<(E,yellow)>>
EdgeTextIconography : numberA : int - nr
EdgeTextIconography : numberB : int - nr
EdgeTextIconography : previewA : str - nr
EdgeTextIconography : previewB : str - nr
EdgeTextIconography : copy_variants : bool - o - nr

class EdgeTextCriterion <<(E,yellow)>>
EdgeTextCriterion : number : int - nr - o 

class EdgeTextOption <<(E,yellow)>>
EdgeTextOption : numberA : int - nr
EdgeTextOption : numberB : int - nr
EdgeTextOption : previewA : str - nr
EdgeTextOption : previewB : str - nr
EdgeTextOption : copy_variants : bool - o - nr

class EdgeTextCycle <<(E,yellow)>>
EdgeTextCycle : numberA : int - nr
EdgeTextCycle : numberB : int - nr
EdgeTextCycle : previewA : str - nr
EdgeTextCycle : previewB : str - nr

Heading "0..n" -- "1" EdgeHeadingText : > has example
EdgeHeadingText "1" -- "0..n" Text :  is example for <

Person "0..n" --- "0..n" Text : > wrote \n written by <

Family "0..n" --- "0..n" Text :  > appears in by\n  describes <

EdgeTextText "1" -- "0..n" Text : has part <
EdgeTextText "1" -- "0 or 1" Text :  part of >

Text "0..n" -- "1" EdgeTextIconography : source of >
EdgeTextIconography "1" -- "0..n" Iconography : source <

Text "0..n" -- "1" EdgeTextCriterion : > can be connected to \n these Criteria 
EdgeTextCriterion "1" -- "1" Criterion : \n Criterion linked to <

Text "0..n" -- "1" EdgeTextOption : addition source of >
EdgeTextOption "1" -- "0..n" Option : additional source <

Text "0..n" -- "1" EdgeTextCycle : related image cycles >
EdgeTextCycle "1" -- "0..n" Cycle : theme of cycle <


Text "0..n" --- "0..n" Manuscript: < illustrated in \n contains illustrations of

Text "0..n" --- "0..n" Book: > illustrated in \n contains illustrations of <

Text "0..n" --- "0..n" Artwork : < illustrates \n illustration of >

Text "0..n" --- "0..n" Matrix : > can be illustration of \n can illustrate <

Text "0..n" --- "0..1 or 0..n" Inscription : < quoted in \n quotes >

@enduml 
