@startuml
title Ingest iif manifest
|UI|
start
:Enter iif url in UI;
:Select resource type (book or manuscript);
|BFF|
#orange:Get iif manifest; 
:Parse manifest;
if (resource type?) then (manuscript)
else (book)
    :Search for bibliographical
    reference in manifest;
    #orange:Get bibliographical
    description for this reference;
    if (found?) then (yes)
    else (no)
        |UI| 
        :Enter bibliographical
        reference;
        note right
        If there is no bibliographical
        reference, information must be
        entered manually, using the
        element_insert_object process
        end note
        |BFF|
        #orange:Get bibliographical
        description for this
        reference;
    end if
    :Parse bibliographical description;
end if
:Get from manifest or
bibligraphical description
 Objects (Persons/Places)
 for search
(search for every Object
separately);
|DB|
:search for Object records;
|BFF|
if (Object records found?) then (yes)
    
else (no)
    #orange:Search for Objects 
    in GND etc.;
    :Parse results;
end if 

|UI|
if (Expected candidates
in list?) then (yes)
else (no)
    :Add terms for
    manual search;
    note right
    currently only GND ID, but 
    other search types also 
    possible (also in the DB)
    endnote
    |BFF|
    #orange:Search for these 
    terms in GND;
    |UI|
    :Result added to list;
endif
:Select Persons
and places amongst the 
candidates;
note right
Something needs to be 
done if no plausible candidate
found in the searches
(enter Object record manually, 
create dummy Object record,
leave out this Object)
endnote
if (User selects medim
from list) then (yes)    
    |BFF|
    :Determines appropriate
    Making processes for 
    this medium, from config file;
    |UI|
    if (User wants to give 
    information on artists
    in any of the processes) then (yes)
        :Fill in
        search box;
        :Process element_insert_object
         is run (involving BFF/DB);
                :Preferred place of activity 
        of artist (from record) is 
        written into Place record and
        shown in Place search box;
        note right
        If the Artist record has just
        been ingested and lacks a preferred
        place of activity, this action must
        be done after the artist record
        has been completed
        end note

    else (no)
    endif
    if (User wants to give 
    information on place of making
    in any of the processes) then (yes)
        :Fill in
        search box;
        note right
        This would overwrite the place
        name entered here automatically
        after giving an artist's name.
        end note

        :Process element_insert_object_
        place_text is run
        (involving BFF/DB);
    else (no)
    endif
    if (User wants to give
    information on date of making
    in any of the processes) then (yes)
        :Fill in
        search box;
        |BFF|
        :Parse data;
        |UI|
        :user checks parsed date;
    else (no)
    endif
else (no)
endif

:Save record;
|BFF|
:Ingest any new 
Authority records;
:Check connections of 
the new records;
if (Connected record
already in database
as full record) then (yes)
elseif (Connected record
already in database as
stub) then (yes)
    #orange:Download and ingest 
    connected record;
    :Upgrade stub to
    full record;
elseif (Connected record
not in database) then (yes)
    if (Full record relevant
    for database) then (yes)
        #orange:Download and ingest
        connected record;
        :Create new full record;
    else (no)
        :Create stub;
    end if
end if 
:Create Edge between the 
Authority record ingested
originally and this new
record;
|DB|
:Store all new Authority
records and Edges between
them;
|BFF|
:Create new Book
or manuscript record;
:Creat new record
of type 'Pages' with 
the data needed for 
the next step of 
the process (1.3.2);
|DB|
:Store new book / 
manuscript and 
Pages records;
note right
error handling
needs to be
considerered
end note
|BFF|
:Success;
|UI|
:Success;
end

@enduml