@startuml
title Select Connected Object Records (execept Place / Text)

|UI|
start
note right
This action will happen
regularly in different
types of views, e.g.
- ingest Book
- ingest Artwork
- edit Artwork
- create/edit Iconography
- create/edit Object
endnote
note right
Each view has fields
for entering those
objects that are
appropriate for the
records, and for each
object a list of 
connection types
endnote
:Select connection type
from list;
note right
this can be done now 
or later
endnote
:Start typing name
of Object (Autocomplete);

repeat
    :Once a minimum of letters
    has been typed, Send this text 
    and the Object type to BFF;
    |BFF|
    :Launch search in DB for
    Objects whose name  
    contains this string;
    |DB|
    :Search;
    |BFF|
    :Process search result
    for display;
    note right
    Add options for 'failed 
    search' (if there are hits, 
    add 'none of these'; if there
    are none, add 'nothing found')
    endnote

    |UI|
    :Display result;

repeat while (User continues typing)

if (Select item from list) then (result)
else ('failed search' option)
    :Launch external search;
    note right
    The external search takes
    several seconds; hence it 
    is better to launch it not
    automatically but let the 
    user launch it for all
    objects with 'failed search'
    selected
    endnote
    note right
    for some types of objects
    (e.g., Actions), there is
    no search in external 
    database
    endnote
    :Send search string and
    Object Type to BFF;
    |BFF|
    #orange:Launch search in 
    appropriate external
    database (e.g., GND);
    :Parse search results;
    note right
    Again with notes
    for 'failed search'
    endnote
    |UI|
    :Display result;
    if (Select from list) then (result)
        
    else ('failed search'
    option)
        :Save all data from this view in FE;
        :Open view Create missing Object
        for appropriate Object type;
        :Once Object records
        has been created manually,
        return to this view;
        :Restore stored data;
        :Automatically insert 
        newly-created object;
    end if

end if

if (New record is 
an iconography record AND 
selected connection already
in the database AND the 
iconographic connections 
related to this record 
are not sorted automatically 
e.g., alphabeticaly)  then (yes)
    |BFF|
    :Launch search for all
    Iconographies of the type
    of the new record connected
    to selected record 
    (directly or indirectly);
    note right
    This 
    step is primarily needed 
    for iconographies. 
    It is only necessary 
    if the record is already
    in the DB, since a newly
    ingested record would not
    have any connected icono-
    graphies yet. In some
    cases, these lists may
    be sorted automatically 
    e.g., alphabetically, then
    this step is not needed.
    end note
    |DB|
    :search;
    |BFF|
    :turn results into 
    structured list;
        |UI|
    :Display list;
    :Select place where
    connection to new
    iconography record
    would fit in;
else (no)
end if
if (Name of matched record
looks odd in list of connections
for new record) then (yes)
    :overwrite name with 
    preview name;
else (no)
end if
if (Name of new iconography record
looks odd in list of connections
for matched record) then (yes)
    :overwrite name with 
    preview name;
else (no)
end if
if (Connection needs a date) then (yes)
    :enter date;
    note right
    e.g., for relationships 
    involving persons (marriage etc.)
    end note
    |BFF|
    :parse date;
    |UI|
    :check date;
    else (no)
    end if



end

@enduml