@startuml
title Creating Iconography Records
|UI|
start
:go to Edit Iconography View;
note right
three different points of departure
- start menu
- Edit Artwork view
- View/Edit Object view
endnote
:Select type of iconography
(portrait, emblem, etc.);
|BFF|
:Determines possible objects, and 
connection types for each object,
for this type of iconography 
according to list in config file;
note right
Objects are e.g. persons, animals,
places, actions, texts
endnote
:Sends these Objects and the 
forms needed for creating
variants to UI;
|UI|
:Enter Object name and
select Connection for each
Object
(see separate diagram -
this includes steps 
in BFF and DB);
note right
Different procedures for
Place / Text objects and
for all other objects
endnote
:For some types of Iconography,
a preferred name for it is created
automatically;
note right
e.g., if type is Portrait and name
is Napoleon, "Portrait of Napoleon"
is created as suggestion
endnote
:Enter (or change) preferred name
and name variants of iconography;
:Enter iconclass notation;
|BFF|
:Search iconclass notation at 
iconclass API, return corresponding
name;
|UI|
:Display name of iconography;
:(if needed)create form for 
variant(s) of this records;
note right
There are two forms a standard
form that is largely filled in with 
the texts for an attribute that may or
may not be present, and a free form that
has to be filled in manually
endnote
:Fill in variant records form;
:if a variant is to be connected to
Objects, enter object records
and connections as above;
:save the record;
|BFF|
:process the record for saving
in the DB;
note right
if Child records for Place and Text
Objects have been created or modified,
they have to be saved, too. 
endnote
|DB|
:save record (including Object
Child records, where applicable);
|BFF|
:success;
|UI|
:success;
:return to place of departure;
end  





@enduml
