@startuml
title Search for Iconography
|UI|
start
:Go to Search Screen;
:Start typing name
of Iconography;

repeat
    :Once a minimum of letters
    has been typed, send them 
    to BFF for Autocomplete;
    |BFF|
    :Launch search in DB for
    Iconography records whose name  
    contains this string
    (Preview only);
    |DB|
    :Search;
    |BFF|   
    
    :Prooces search result
    for display;
    |UI|
    :Display result;
repeat while (User continues typing)
:Select one
or more results;
|BFF|
:Launch search for selected
Iconography records
(complete, with all
connected records);
|DB|
:Search;
|BFF|
:Launch search for 
all Image records
with this Iconography
(with connected 
Artwork, Copy, and Photo
Records);
|DB|
:Search;
|BFF|
:Determine terms
for sorting, grouping
or filtering records
according to 
- Medium
- Creation Date 
- Artist 
- Place of Making
 (with Child records)
- Illustrated text 
- Iconography 
 (if the search
   was for more than one
   Iconography)
 - Variants of each
   Iconography;
:Sort records by date
 (as default);
 :Limit results to the 
 maximum size of hits 
 on a page;
 
|UI|
:Show search results
 (mainly preview images
  in mosaic view, plus 
  content of Iconography
  record, at least abbreviated);
:Show criteria for
filtering/sorting/grouping 
as provided by BFF
(the displayed options
depend on search result);

if (User wants next page
or results) then (yes)
    |BFF|
    :Execute new search
    (as above);
    :Sort results
    as before;
    :Limit results to the
    next page that can be
    displayed;
    |UI|
    :Display new result;
else
end if 

if (User filters, groups 
or orders results) then (yes)
    |BFF|
    :Execute new search
    (as above);
    :Sort results as 
    desired;
    |UI|
    :Display new result;
else
end if 

if (User selects a record) then (yes)
    |BFF|
    :Search this record
    (see separate diagram);
    |UI|
    :Go to single Artwork 
    display;
    end
else
end if 

if (User selects an
Iconography record) then (yes)
    |BFF|
    :Search this record
    (see separate diagram);
    |UI|
    :Go to single Record 
    display;
    end
else
end if 

if (User launches a new search
for a property displayed somewhere) then (yes)
    |BFF|
    :Execute new search
    (as above);
    :Sort results as 
    desired;
    |UI|
    :Display new result;
else
end if 


if (user selects an
Iconography record) then (yes)
    |BFF|
    :Search this record
    (see separate diagram);
    |UI|
    :Go to single Record 
    display;
    note right
    An editor can
    also open the
    record in Edit
    view. 

    end note
    end
else
end if 


:Editor can additionally
 do the following:
- open the full Iconography
    record for editing
- open one Artwork record 
    for editing
- select a number of Artwork
    records and open
    them for bulk editing;



@enduml
