@startuml
title Search for Iconographies connected to specific Objects (e.g. all narratives involving a person)
|UI|
start
:Go to Search Screen;
:User chooses type of Object;
:User starts typing name
of Object;

repeat
    :Once a minimum of letters
    has been typed, send them
    with the Object type to BFF;
    |BFF|
    :Launch search in DB for
    Object records of the right
    type whose name  
    contains this string
    (Preview only);
    |DB|
    :search;
    |BFF|   
    
    :Send all found records to UI;
    |UI|
    :Display result;
repeat while (User continues typing)
:User selects one
or more results;
:Send the selected
record Ids to BFF;
|BFF|
:Launch search for selected
Object records
(complete, with all
connected records);
|DB|
:Search;
|BFF|
if (record type is
Place or Text) then (yes)
    :search also for their
    Child records (recursive);
    |DB|
    :search;
    |BFF|
else (no)
end if 
:search for all Iconography
records connected to any of 
these records;
|DB|
:search;

|BFF|
:Launch search for 
all Image records
with these Iconographies
(with connected 
Artwork, Copy, and Photo
Records);
|DB|
:Search;
|BFF|
:Index (for lack of a 
better word) result 
records that they can 
be sorted, grouped 
or filtered
according to 
- Medium
- Creation Date 
- Artist 
- Place of Making
 (with Child records)
- Illustrated text 
- Depicted Object
    (if the search
    was for more than
    one Object)
- Iconography 
 (if the search
   was for more than one
   Iconography)
 - Variants of each
   Iconography;
:Sort records by date
 (as default);
|UI|
:Show search results
 (mainly preview images
  in mosaic view, plus 
  content of Iconography
  record, at least abbreviated);
:Show possibilities for
filtering/sorting/grouping 
as provided by BFF
(the displayed options
depend on search result);

:User can do the
following:
- filter results according
   to one or more criteria
- group results according
   to one criterion 
   (more makes little sense)
- sort results according to
   one or more criteria
- display a detail view of one
   Artwork record
- display the full Iconography 
    record
- launch new searches;

:Editor can also do
the following:
- open the full Iconography
    record for editing
- open one Artwork record 
    for editing
- select a number of Artwork
    records and open
    them for bulk editing;



@enduml
